title: Beta Fleet
description: Welcome to Beta Fleet! Beta Fleet is a traditional based fictional airline that provides fast and comfortable travel for all passengers. Our priority is your comfort and well being, we guarantee the best quality flights and safe travel for all passengers including excellent services. Beta Fleet was established on 4/12/16 by AviaWill.

theme: jekyll-theme-cayman
